### ISSUE TITLE
Mismatched number of DMR labels

### ISSUE THREAD

**Issue by hanyangii** [CompEpigen/methylbert#11]
```
Traceback (most recent call last):
  File "/omics/groups/OE0219/internal/Yunhee/anaconda3/envs/methylbert_39/bin/methylbert", line 33, in <module>
    sys.exit(load_entry_point('methylbert', 'console_scripts', 'methylbert')())
  File "/omics/groups/OE0219/internal/Yunhee/DL_project/methylbert/src/cli.py", line 287, in main
    run_deconvolute(args)
  File "/omics/groups/OE0219/internal/Yunhee/DL_project/methylbert/src/cli.py", line 211, in run_deconvolute
    trainer.load(restore_dir, 
  File "/omics/groups/OE0219/internal/Yunhee/DL_project/methylbert/src/methylbert/trainer.py", line 625, in load
    self.bert = MethylBertEmbeddedDMR.from_pretrained(dir_path, 
  File "/omics/groups/OE0219/internal/Yunhee/anaconda3/envs/methylbert_39/lib/python3.9/site-packages/transformers/modeling_utils.py", line 3960, in from_pretrained
    ) = cls._load_pretrained_model(
  File "/omics/groups/OE0219/internal/Yunhee/anaconda3/envs/methylbert_39/lib/python3.9/site-packages/transformers/modeling_utils.py", line 4492, in _load_pretrained_model
    raise RuntimeError(f"Error(s) in loading state_dict for {model.__class__.__name__}:\n\t{error_msg}")
RuntimeError: Error(s) in loading state_dict for MethylBertEmbeddedDMR:
        size mismatch for dmr_encoder.0.weight: copying a param with shape torch.Size([100, 151]) from checkpoint, the shape in current model is torch.Size([97, 151]).
        You may consider adding `ignore_mismatched_sizes=True` in the model `from_pretrained` method.
```

**Comment by hanyangii** [comment]
solved by fixing the bug about num_dmrs (https://github.com/CompEpigen/methylbert/commit/a2eca9320c77a1554c9806b2cd7d6d992e328f97)
