### ISSUE TITLE
pysam installation in python 3.11

### ISSUE THREAD

**Issue by hanyangii** [CompEpigen/methylbert#14]
```
(methylbert_311) pip3 install pysam
Collecting pysam
  Using cached pysam-0.22.1.tar.gz (4.6 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [170 lines of output]
      # pysam: cython is available - using cythonize if necessary
      # pysam: htslib mode is shared
      # pysam: HTSLIB_CONFIGURE_OPTIONS=None
      # pysam: (sysconfig) CC=gcc -pthread -B /omics/groups/OE0219/internal/Yunhee/anaconda3/envs/methylbert_311/compiler_compat
      # pysam: (sysconfig) CFLAGS=-DNDEBUG -fwrapv -O2 -Wall   -fPIC   -O2 -isystem /omics/groups/OE0219/internal/Yunhee/anaconda3/envs/methylbert_311/include -fPIC -O2   -isystem /omics/groups/OE0219/internal/Yunhee/anaconda3/envs/methylbert_311/include  -fPIC
      # pysam: (env) LDFLAGS=-Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,--disable-new-dtags -Wl,--gc-sections -Wl,-rpath,/omics/groups/OE0219/internal/Yunhee/anaconda3/lib -Wl,-rpath-link,/omics/groups/OE0219/internal/Yunhee/anaconda3/lib -L/omics/groups/OE0219/internal/Yunhee/anaconda3/lib
      checking for gcc... gcc -pthread -B /omics/groups/OE0219/internal/Yunhee/anaconda3/envs/methylbert_311/compiler_compat
      checking whether the C compiler works... yes
      checking for C compiler default output file name... a.out
      checking for suffix of executables...
      checking whether we are cross compiling... no
      checking for suffix of object files... o
      checking whether we are using the GNU C compiler... yes
      checking whether gcc -pthread -B /omics/groups/OE0219/internal/Yunhee/anaconda3/envs/methylbert_311/compiler_compat accepts -g... yes
      checking for gcc -pthread -B /omics/groups/OE0219/internal/Yunhee/anaconda3/envs/methylbert_311/compiler_compat option to accept ISO C89... none needed
      checking for ranlib... ranlib
      checking for grep that handles long lines and -e... /usr/bin/grep
      checking for C compiler warning flags... unknown
      checking how to run the C preprocessor... gcc -pthread -B /omics/groups/OE0219/internal/Yunhee/anaconda3/envs/methylbert_311/compiler_compat -E
      checking for egrep... /usr/bin/grep -E
      checking for ANSI C header files... yes
      checking for sys/types.h... yes
      checking for sys/stat.h... yes
      checking for stdlib.h... yes
      checking for string.h... yes
      checking for memory.h... yes
      checking for strings.h... yes
      checking for inttypes.h... yes
      checking for stdint.h... yes
      checking for unistd.h... yes
      checking whether _XOPEN_SOURCE is declared... no
      checking C compiler flags needed for ssse3... -mssse3
      checking C compiler flags needed for popcnt... -mpopcnt
      checking C compiler flags needed for sse4.1... -msse4.1
      checking C compiler flags needed for avx2... -mavx2
      checking C compiler flags needed for avx512f... unsupported
      checking for pkg-config... /usr/bin/pkg-config
      checking pkg-config is at least version 0.9.0... yes
      checking for special C compiler options needed for large files... no
      checking for _FILE_OFFSET_BITS value needed for large files... no
      checking shared library type for unknown-Linux... plain .so
      checking whether the linker supports versioned symbols... no
      checking whether the compiler accepts -fvisibility=hidden... yes
      checking for stdlib.h... (cached) yes
      checking for unistd.h... (cached) yes
      checking for sys/param.h... yes
      checking for getpagesize... yes
      checking for working mmap... yes
      checking for gmtime_r... yes
      checking for fsync... yes
      checking for drand48... yes
      checking for srand48_deterministic... no
      checking whether fdatasync is declared... yes
      checking for fdatasync... yes
      checking for library containing log... -lm
      checking for zlib.h... yes
      checking for inflate in -lz... yes
      checking for library containing recv... none required
      checking for bzlib.h... yes
      checking for BZ2_bzBuffToBuffCompress in -lbz2... yes
      checking for lzma.h... yes
      checking for lzma_easy_buffer_encode in -llzma... no
      configure: error: liblzma development files not found
      
      The CRAM format may use LZMA2 compression, which is implemented in HTSlib
      by using compression routines from liblzma <http://tukaani.org/xz/>.
      
      Building HTSlib requires liblzma development files to be installed on the
      build machine; you may need to ensure a package such as liblzma-dev (on Debian
      or Ubuntu Linux), xz-devel (on RPM-based Linux distributions or Cygwin), or
      xz (via Homebrew on macOS) is installed; or build XZ Utils from source.
      
      Either configure with --disable-lzma (which will make some CRAM files
      produced elsewhere unreadable) or resolve this error to build HTSlib.
      checking for gcc... gcc -pthread -B /omics/groups/OE0219/internal/Yunhee/anaconda3/envs/methylbert_311/compiler_compat
      checking whether the C compiler works... yes
      checking for C compiler default output file name... a.out
      checking for suffix of executables...
      checking whether we are cross compiling... no
      checking for suffix of object files... o
      checking whether we are using the GNU C compiler... yes
      checking whether gcc -pthread -B /omics/groups/OE0219/internal/Yunhee/anaconda3/envs/methylbert_311/compiler_compat accepts -g... yes
      checking for gcc -pthread -B /omics/groups/OE0219/internal/Yunhee/anaconda3/envs/methylbert_311/compiler_compat option to accept ISO C89... none needed
      checking for ranlib... ranlib
      checking for grep that handles long lines and -e... /usr/bin/grep
      checking for C compiler warning flags... unknown
      checking how to run the C preprocessor... gcc -pthread -B /omics/groups/OE0219/internal/Yunhee/anaconda3/envs/methylbert_311/compiler_compat -E
      checking for egrep... /usr/bin/grep -E
      checking for ANSI C header files... yes
      checking for sys/types.h... yes
      checking for sys/stat.h... yes
      checking for stdlib.h... yes
      checking for string.h... yes
      checking for memory.h... yes
      checking for strings.h... yes
      checking for inttypes.h... yes
      checking for stdint.h... yes
      checking for unistd.h... yes
      checking whether _XOPEN_SOURCE is declared... no
      checking C compiler flags needed for ssse3... -mssse3
      checking C compiler flags needed for popcnt... -mpopcnt
      checking C compiler flags needed for sse4.1... -msse4.1
      checking C compiler flags needed for avx2... -mavx2
      checking C compiler flags needed for avx512f... unsupported
      checking for pkg-config... /usr/bin/pkg-config
      checking pkg-config is at least version 0.9.0... yes
      checking for special C compiler options needed for large files... no
      checking for _FILE_OFFSET_BITS value needed for large files... no
      checking shared library type for unknown-Linux... plain .so
      checking whether the linker supports versioned symbols... no
      checking whether the compiler accepts -fvisibility=hidden... yes
      checking for stdlib.h... (cached) yes
      checking for unistd.h... (cached) yes
      checking for sys/param.h... yes
      checking for getpagesize... yes
      checking for working mmap... yes
      checking for gmtime_r... yes
      checking for fsync... yes
      checking for drand48... yes
      checking for srand48_deterministic... no
      checking whether fdatasync is declared... yes
      checking for fdatasync... yes
      checking for library containing log... -lm
      checking for zlib.h... yes
      checking for inflate in -lz... yes
      checking for library containing recv... none required
      checking for bzlib.h... yes
      checking for BZ2_bzBuffToBuffCompress in -lbz2... yes
      checking for lzma.h... yes
      checking for lzma_easy_buffer_encode in -llzma... no
      configure: error: liblzma development files not found
      
      The CRAM format may use LZMA2 compression, which is implemented in HTSlib
      by using compression routines from liblzma <http://tukaani.org/xz/>.
      
      Building HTSlib requires liblzma development files to be installed on the
      build machine; you may need to ensure a package such as liblzma-dev (on Debian
      or Ubuntu Linux), xz-devel (on RPM-based Linux distributions or Cygwin), or
      xz (via Homebrew on macOS) is installed; or build XZ Utils from source.
      
      Either configure with --disable-lzma (which will make some CRAM files
      produced elsewhere unreadable) or resolve this error to build HTSlib.
      config.mk:2: *** Resolve configure error first.  Stop.
      # pysam: htslib configure options: None
      Traceback (most recent call last):
        File "/omics/groups/OE0219/internal/Yunhee/anaconda3/envs/methylbert_311/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/omics/groups/OE0219/internal/Yunhee/anaconda3/envs/methylbert_311/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/omics/groups/OE0219/internal/Yunhee/anaconda3/envs/methylbert_311/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-ftjtbw8x/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 333, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-ftjtbw8x/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 303, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-ftjtbw8x/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 521, in run_setup
          super().run_setup(setup_script=setup_script)
        File "/tmp/pip-build-env-ftjtbw8x/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 319, in run_setup
          exec(code, locals())
        File "<string>", line 437, in <module>
        File "<string>", line 81, in run_make_print_config
        File "/omics/groups/OE0219/internal/Yunhee/anaconda3/envs/methylbert_311/lib/python3.11/subprocess.py", line 466, in check_output
          return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/omics/groups/OE0219/internal/Yunhee/anaconda3/envs/methylbert_311/lib/python3.11/subprocess.py", line 571, in run
          raise CalledProcessError(retcode, process.args,
      subprocess.CalledProcessError: Command '['make', '-s', 'print-config']' returned non-zero exit status 2.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

With the python 3.11 environment, lzma makes a problem while pysam is being installed.

**Comment by hanyangii** [comment]
It was the limited conda service term (non-commercial use). 
Removed default channels following [this](https://stackoverflow.com/questions/67695893/how-do-i-completely-purge-and-disable-the-default-channel-in-anaconda-and-switch/67708768#67708768):
```
conda config --show channels
conda config --remove channels defaults
conda config --add channels conda-forge
```

And then created a new conda environment with python 3.11.

**Comment by hanyangii** [comment]
Hello @AndriesDeKoker 

Thank you for your comment! Recently, there have been major changes in conda, I think. 
If you still struggle with your installation issues and want me to take a look, could you please copy-paste your error messages? It would be easier for me to understand the situation better :)

**Comment by AndriesDeKoker** [comment]
Well, I switched to a linux system and there I got it installed. However I can only use it as a python package for now, not on bash. I don't know why.

I abandoned looking further into the install on MacOS because of the cudatools issue. I will try again soon

**Comment by hanyangii** [comment]
Oh I see, thank you very much for the update!
Please feel free to ask me anytime if you need further discussion about the problem :)
